- numpy에서 자주 사용되는 함수들을 사용해보기

In [18]:
import numpy as np

### numpy documentation
- [numpy 공식 문서 링크](https://numpy.org/)
- numpy에서 제공되는 함수등에 대한 문서

In [11]:
x = np.arange(15).reshape(3,5)
y = np.random.rand(15).reshape(3,5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.25006723 0.12661945 0.04555148 0.05804673 0.03759384]
 [0.41915328 0.46237438 0.57630336 0.17450314 0.45195708]
 [0.63690356 0.72843066 0.35549306 0.97282448 0.5154975 ]]


### 연산함수
- add, subtract, multiply, divide

In [12]:
np.add(x, y)

array([[ 0.25006723,  1.12661945,  2.04555148,  3.05804673,  4.03759384],
       [ 5.41915328,  6.46237438,  7.57630336,  8.17450314,  9.45195708],
       [10.63690356, 11.72843066, 12.35549306, 13.97282448, 14.5154975 ]])

In [22]:
#np.subtract(x, y)
#np.multiply(x, y)
#np.divide(x, y)

In [16]:
x + y

array([[ 0.25006723,  1.12661945,  2.04555148,  3.05804673,  4.03759384],
       [ 5.41915328,  6.46237438,  7.57630336,  8.17450314,  9.45195708],
       [10.63690356, 11.72843066, 12.35549306, 13.97282448, 14.5154975 ]])

In [17]:
x - y

array([[-0.25006723,  0.87338055,  1.95444852,  2.94195327,  3.96240616],
       [ 4.58084672,  5.53762562,  6.42369664,  7.82549686,  8.54804292],
       [ 9.36309644, 10.27156934, 11.64450694, 12.02717552, 13.4845025 ]])

In [23]:
x / y

array([[  0.        ,   7.89768105,  43.90637081,  51.68249612,
        106.40042253],
       [ 11.92881028,  12.97649762,  12.14638076,  45.84444796,
         19.91339515],
       [ 15.7009642 ,  15.10095682,  33.75593323,  13.36315054,
         27.15823039]])

### 통계 함수
- 평균, 분산, 중앙, 최대, 최솟값... 통계 관련된 함수가 내장

In [24]:
print(y)

[[0.25006723 0.12661945 0.04555148 0.05804673 0.03759384]
 [0.41915328 0.46237438 0.57630336 0.17450314 0.45195708]
 [0.63690356 0.72843066 0.35549306 0.97282448 0.5154975 ]]


In [25]:
np.mean(y)

0.38742128211366944

In [26]:
y.mean()

0.38742128211366944

In [27]:
np.max(y)

0.9728244821088881

In [29]:
#max index
np.argmax(y)

13

In [30]:
np.var(y), np.median(y), np.std(y)

(0.07100496707153296, 0.4191532838724952, 0.2664675722701225)

### 집계함수
- 합계(sum), 누적합계(cumsum) 등등 계산 가능

In [31]:
np.sum(y)

5.811319231705042

In [38]:
#축을 직접 설정할 수 있다.
np.sum(y, axis = None)#기본값
np.sum(y, axis = 0)
np.sum(y, axis = 1)

array([0.51787872, 2.08429124, 3.20914927])

In [34]:
#누적합
np.cumsum(y)

array([0.25006723, 0.37668668, 0.42223815, 0.48028489, 0.51787872,
       0.93703201, 1.39940638, 1.97570974, 2.15021288, 2.60216996,
       3.23907352, 3.96750418, 4.32299724, 5.29582173, 5.81131923])

### any, all 함수
- any : 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
- all : 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [39]:
z = np.random.randn(10)
print(z)

[ 0.62722706  0.80074063  0.34186381  0.30162773  0.74909184  0.66938615
  0.83052428  0.10144507 -0.32985623  0.98568481]


In [40]:
# 하나라도 만족한다면 True
np.any(z > 0)

True

In [41]:
z > 0

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        True])

In [43]:
# 모두 만족해야 True
print(np.all(z > 0))
print(np.all(z != 0))

False
True


### where 함수
- 조건에 따라 선별적으로 값을 선택 가능
- 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [44]:
z = np.random.randn(10)
print(z)

[-0.77753501 -0.31071433  0.47746329  1.27018905 -1.2072043  -0.75039673
  1.40665048 -1.07161637  0.61091474 -2.03385709]


In [46]:
np.where(z > 0, z, 0 )

array([0.        , 0.        , 0.47746329, 1.27018905, 0.        ,
       0.        , 1.40665048, 0.        , 0.61091474, 0.        ])

In [48]:
np.where(z < 0, z, 0)

array([-0.77753501, -0.31071433,  0.        ,  0.        , -1.2072043 ,
       -0.75039673,  0.        , -1.07161637,  0.        , -2.03385709])

### axis(축)이란? axis를 파라미터로 갖는 함수 활용하는 방법

### axis란?
- 몇몇 함수에는 axis keyword 파라미터가 존재한다
- axis 값이 없는 경우에는 전체 데이터에 대해 적용
- axis 값이 있는 경우에는, 해당 axis를 따라서 연산 작용한다.

- axis를 파라미터로 갖는 함수를 이용하기
    - 거의 대부분의 연산 함수들이 axis 파라미터를 사용
    - 이 경우, 해당 값이 주어졌을 때, 해당 axis를 따라서 연산이 적용
        - 따라서 결과는 해당 axis가 제외된 나머지 차원의 데이터만 남게 된다.
    - 예) np.sum, np.mean, np.any 등등

In [50]:
x = np.arange(15)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


- 1차원 데이터에 적용하기

In [54]:
np.sum(x, axis = 0)

105

- 행렬에 적용하는 방법

In [66]:
y = x.reshape(3, 5)
print(y)
print(np.sum(y))
print(np.sum(y, axis=0)) #행방향 상하
print(np.sum(y, axis=1)) #열방향 좌우

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
105
[15 18 21 24 27]
[10 35 60]


- 3차원 텐서에 적용하는 방법

In [68]:
z = np.arange(36).reshape(3,4,3)
print(z)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [69]:
np.sum(z, axis = 0)

array([[36, 39, 42],
       [45, 48, 51],
       [54, 57, 60],
       [63, 66, 69]])

In [70]:
np.sum(z, axis = 1)

array([[ 18,  22,  26],
       [ 66,  70,  74],
       [114, 118, 122]])

In [74]:
print(np.sum(z, axis = 2))
print(np.sum(z, axis = -1))
print(np.sum(z, axis = -3))

[[  3  12  21  30]
 [ 39  48  57  66]
 [ 75  84  93 102]]
[[  3  12  21  30]
 [ 39  48  57  66]
 [ 75  84  93 102]]
[[36 39 42]
 [45 48 51]
 [54 57 60]
 [63 66 69]]


- axis의 값이 튜플인 경우
    - 해당 튜플에 명시된 모든 axis에 대해서 연산

In [75]:
print(z)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [76]:
np.sum(z, axis = (0, 1))

array([198, 210, 222])

In [77]:
np.sum(z, axis = (0, 2))

array([117, 144, 171, 198])