In [1]:
import numpy as np

### np.linalg.inv
- 역행렬을 구할 때 사용
- 모든 차원의 값이 같아야 함

In [5]:
x = np.random.rand(3, 3)
print(x)

np.matmul(x,np.linalg.inv(x))
x @ np.linalg.inv(x)

[[0.27330838 0.28623136 0.40715075]
 [0.47842376 0.57722352 0.68411335]
 [0.84931421 0.42707145 0.23858817]]


array([[ 1.00000000e+00, -2.50767553e-16, -3.28276058e-17],
       [-1.47157064e-15,  1.00000000e+00, -4.95781530e-17],
       [ 1.26228114e-16,  2.38153416e-16,  1.00000000e+00]])

### np.linalg.solve
- Ax = B 형태의 선형대수식 솔루션을 제공한다
- 예) 강아지와 비둘기의 합 : 총 25마리 강아지 다리와 비둘기의 다리 합은 64

- x + y = 25
- 2x + 4y = 64

In [10]:
A = np.array([[1,1],[2,4]])
B = np.array([25, 64])

x = np.linalg.solve(A,B)
print(x)

#실수값 비교 방법
print(np.allclose(A@x, B))

[18.  7.]
True
